version: 2.1

executors:
  gfortran:
    docker:
      - image: gmao/ubuntu20-geos-env-mkl:v6.2.8-openmpi_4.0.6-gcc_11.2.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_AUTH_TOKEN
    environment:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      MPIEXEC_PREFLAGS: --oversubscribe
    resource_class: large
    #MEDIUM# resource_class: medium

  ifort:
    docker:
      - image: gmao/ubuntu20-geos-env:v6.2.8-intelmpi_2021.2.0-intel_2021.2.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_AUTH_TOKEN
    resource_class: large
    #MEDIUM# resource_class: medium

workflows:
  build-test:
    jobs:
      - build-GEOSgcm:
          name: build-GEOSgcm-on-<< matrix.compiler >>
          matrix:
            parameters:
              compiler: [gfortran, ifort]
          context: 
            - docker-hub-creds
      ###################################################
      # - make-FV3-exp:                                 #
      #     name: make-FV3-exp-on-<< matrix.compiler >> #
      #     matrix:                                     #
      #       parameters:                               #
      #         compiler: [gfortran, ifort]             #
      #     context:                                    #
      #       - docker-hub-creds                        #
      #     requires:                                   #
      #       - build-GEOSgcm-on-<< matrix.compiler >>  #
      # - run-FV3:                                      #
      #     name: run-FV3-on-<< matrix.compiler >>      #
      #     matrix:                                     #
      #       parameters:                               #
      #         compiler: [gfortran, ifort]             #
      #     context:                                    #
      #       - docker-hub-creds                        #
      #     requires:                                   #
      #       - make-FV3-exp-on-<< matrix.compiler >>   #
      ###################################################

commands:
  versions:
    description: "Versions, etc."
    parameters:
      compiler:
        type: string
    steps:
      - run:
          name: "Versions, etc."
          command: | 
            mpirun --version && << parameters.compiler >> --version && echo $BASEDIR && pwd && ls && echo "$(nproc)"

  compress_artifacts:
    description: "Compress artifacts"
    steps:
      - run:
          name: "Compress artifacts"
          command: |
            gzip -9 /logfiles/*

  checkout_fixture:
    description: "Checkout fixture"
    parameters:
      repo:
        type: string
    steps:
      - run:
          name: "Checkout fixture"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}
            git clone https://github.com/GEOS-ESM/<< parameters.repo >>.git

  mepoclone:
    description: "Mepo clone external repos"
    parameters:
      repo:
        type: string
    steps:
      - run:
          name: "Mepo clone external repos"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/<< parameters.repo >>
            mepo clone
            mepo status

  mepodevelop:
    description: "Mepo develop GEOSgcm_GridComp GEOSgcm_App GMAO_Shared"
    parameters:
      repo:
        type: string
    steps:
      - run:
          name: "Mepo develop GEOSgcm_GridComp GEOSgcm_App GMAO_Shared"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/<< parameters.repo >>
            mepo develop GEOSgcm_GridComp GEOSgcm_App GMAO_Shared
            mepo status

  checkout_feature_branch:
    description: "Mepo checkout-if-exists feature branch"
    parameters:
      repo:
        type: string
    steps:
      - run:
          name: "Mepo checkout-if-exists feature branch"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/<< parameters.repo >>
            echo "${CIRCLE_BRANCH}"
            if [ "${CIRCLE_BRANCH}" != "develop" ] && [ "${CIRCLE_BRANCH}" != "main" ]
            then
                mepo checkout-if-exists ${CIRCLE_BRANCH}
            fi
            mepo status

  cmake:
    description: "Run CMake"
    parameters:
      repo:
        type: string
      compiler:
        type: string
    steps:
      - run:
          name: "Run CMake"
          command: |
            mkdir -p /logfiles
            cd ${CIRCLE_WORKING_DIRECTORY}/<< parameters.repo >>
            mkdir -p ${CIRCLE_WORKING_DIRECTORY}/workspace/build-<< parameters.repo >>
            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/build-<< parameters.repo >>
            cmake ${CIRCLE_WORKING_DIRECTORY}/<< parameters.repo >> -DBASEDIR=$BASEDIR/Linux -DCMAKE_Fortran_COMPILER=<< parameters.compiler >> -DCMAKE_BUILD_TYPE=Debug -DUSE_F2PY=OFF -DMPIEXEC_PREFLAGS=${MPIEXEC_PREFLAGS} -DCMAKE_INSTALL_PREFIX=${CIRCLE_WORKING_DIRECTORY}/workspace/install-<< parameters.repo >> |& tee /logfiles/cmake.log

  buildinstall:
    description: "Build and install"
    parameters:
      repo:
        type: string
    steps:
      - run:
          name: "Build and install"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/build-<< parameters.repo >>
            make -j"$(nproc)" install |& tee /logfiles/make.log
            #MEDIUM# make -j4 install |& tee /logfiles/make.log

jobs:
  build-GEOSgcm:
    parameters:
      compiler:
        type: string
    executor: << parameters.compiler >>
    working_directory: /root/project
    steps:
      - run:
          name: "GMAO_Shared branch"
          command: echo ${CIRCLE_BRANCH}
      - checkout_fixture:
          repo: GEOSgcm
      - versions:
          compiler: << parameters.compiler >>
      - mepoclone:
          repo: GEOSgcm
      - mepodevelop:
          repo: GEOSgcm
      - checkout_feature_branch:
          repo: GEOSgcm
      - cmake:
          repo: GEOSgcm
          compiler: << parameters.compiler >>
      - buildinstall:
          repo: GEOSgcm
      - compress_artifacts
      - store_artifacts:
          path: /logfiles
      ###########################
      # - persist_to_workspace: #
      #     root: workspace     #
      #     paths:              #
      #       - install-GEOSgcm #
      ###########################

  make-FV3-exp:
    parameters:
      compiler:
        type: string
    executor: << parameters.compiler >>
    working_directory: /root/project
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: "Run fv3_setup"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/install-GEOSgcm/bin

            INPUT_FOR_SETUP=$(cat \<<END_HEREDOC
            test-fv3-c12
            test-fv3-c12
            12
            72
            NO
            NO
            ${CIRCLE_WORKING_DIRECTORY}/workspace/test-fv3-c12
            NULL
            END_HEREDOC
            )
            echo "$INPUT_FOR_SETUP" > /tmp/input.txt

            cat /tmp/input.txt | ./fv3_setup
      - run:
          name: "Change FV_NX, FV_NY, and RUN_CMD"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/test-fv3-c12
            sed -i.bak -e '/set FV_NX/ s/\([0-9]\+\)/1/' -e '/set FV_NY/ s/\([0-9]\+\)/6/' -e '/set RUN_CMD/ c\set RUN_CMD = "mpirun -np "' fv3.j
      - run:
          name: "Cat fv3.j"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/test-fv3-c12
            cat fv3.j

      # We need to persist the install for the next step
      - persist_to_workspace:
          root: workspace
          paths:
            - test-fv3-c12

  run-FV3:
    parameters:
      compiler:
        type: string
    executor: << parameters.compiler >>
    working_directory: /root/project
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: "Run fv3.j"
          command: |
            mkdir -p /logfiles
            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/test-fv3-c12
            ./fv3.j |& tee /logfiles/fv3_run.log
      - run:
          name: "Check for EGRESS"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/test-fv3-c12

            # The scratch directory for fv3 standalone isn't consistent
            SCRDIR=$(find . -type d -name 'scratch*')

            if [[ -f $SCRDIR/EGRESS ]]
            then
               echo "EGRESS found!"
            else
               echo "EGRESS not found!"
               exit 1
            fi
      - compress_artifacts
      - store_artifacts:
          path: /logfiles

